# Generated by Django 4.0.6 on 2022-07-14 13:40

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_Title', models.CharField(max_length=200)),
                ('song_Body', models.TextField()),
                ('song_Video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'song',
            },
        ),
    ]
