# Generated by Django 4.0.6 on 2022-07-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songrequestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_Video',
            new_name='song_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_Body',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_Title',
        ),
    ]
