# Generated by Django 4.0.6 on 2022-07-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrequestapp', '0003_song_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_duration',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='song_thumbnail',
            field=models.TextField(default=''),
        ),
    ]
