# Generated by Django 4.0.6 on 2022-08-08 17:24

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('songrequestapp', '0004_song_song_duration_song_song_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='songs_play_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_url', embed_video.fields.EmbedVideoField()),
                ('song_title', models.TextField(default='No title')),
                ('song_duration', models.TextField(default='')),
                ('song_thumbnail', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='skip_requests',
            field=models.IntegerField(default=0),
        ),
    ]
