# Generated by Django 4.0.6 on 2022-09-27 11:14

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('songrequestapp', '0005_songs_play_history_song_skip_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='songs_blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_url', embed_video.fields.EmbedVideoField()),
                ('song_title', models.TextField(default='No title')),
                ('song_duration', models.TextField(default='')),
                ('song_thumbnail', models.TextField(default='')),
            ],
        ),
    ]
