# Generated by Django 4.1.5 on 2023-02-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrequestapp', '0008_rename_user_status_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='bug_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
